"""
SIP Data Analyzer Tool (SDAT)
Automated analysis tool for Spectral Induced Polarization data generated by the SIP Instrument (O&E PSIP)
"""
# ============================================================================
#IMPORTS
# ============================================================================

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
import io
import logging
import re
from typing import Tuple, Optional, Dict, List
from enum import Enum

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ============================================================================
# CONSTANTS
# ============================================================================
DEFAULT_REF_RESISTOR = 100.0  # Ohms
DEFAULT_SAMPLE_LENGTH = 0.03   # meters
DEFAULT_SAMPLE_AREA = 0.002    # square meters
HEADER_MARKER = '***End_Of_Header***'
RESISTOR_KEY = 'Current Resistor[Ohms]'
MIN_RESISTIVITY_THRESHOLD = 1e-6  # Ohm-m, minimum value to avoid division issues
CELL_CONSTANT_FACTOR = 0.1606  # Geometric factor for cell constant calculation

# ============================================================================
#STREAMLIT PAGE CONFIGURATION
# ============================================================================

# Page configuration
st.set_page_config(
    page_title="SDAT The SIP Data Analyzer Tool",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# FILE FORMAT DETECTION
# ============================================================================

class FileFormat(Enum):
    """Enumeration of supported file formats."""
    OE_PSIP = "OE_PSIP"
    SIMPLE_TABLE = "SIMPLE_TABLE"
    UNKNOWN = "UNKNOWN"


def detect_file_format(lines: list) -> FileFormat:
    """Detect the format of the uploaded file."""
    header_content = '\n'.join(lines[:min(20, len(lines))])
    
    if HEADER_MARKER in header_content or 'OE PSIP Measurement' in header_content:
        logger.info("Detected format: OE PSIP")
        return FileFormat.OE_PSIP
    
    if any(re.search(r'freq.*hz', line, re.IGNORECASE) for line in lines[:5]):
        logger.info("Detected format: SIMPLE_TABLE")
        return FileFormat.SIMPLE_TABLE
    
    logger.warning("Unknown file format")
    return FileFormat.UNKNOWN


def find_header_end(lines: list) -> int:
    """Find the index of the LAST header end marker in the file."""
    last_marker_idx = -1
    for i, line in enumerate(lines):
        if HEADER_MARKER in line:
            last_marker_idx = i
    return last_marker_idx


def extract_resistor_value(lines: list) -> Tuple[float, bool]:
    """Extract reference resistor value from file metadata."""
    for line in lines:
        if RESISTOR_KEY in line:
            try:
                value = float(line.split(',')[1])
                logger.info(f"Found reference resistor: {value} Ohms")
                return value, True
            except (IndexError, ValueError) as e:
                logger.warning(f"Failed to parse resistor value: {e}")
    
    logger.warning(f"Resistor value not found, using default: {DEFAULT_REF_RESISTOR} Ohms")
    return DEFAULT_REF_RESISTOR, False


def build_column_headers(channel_line: str, column_line: str) -> list:
    """Build combined column headers from channel and column name lines."""
    channel_tokens = channel_line.strip().split(',')
    col_tokens = column_line.strip().split(',')
    
    max_len = max(len(channel_tokens), len(col_tokens))
    channel_tokens += [''] * (max_len - len(channel_tokens))
    col_tokens += [''] * (max_len - len(col_tokens))
    
    unique_columns = []
    for ch, col in zip(channel_tokens, col_tokens):
        col = col.strip()
        ch = ch.strip()
        if ch:
            unique_columns.append(f"{ch} {col}")
        else:
            unique_columns.append(col)
    
    unique_columns = [c for c in unique_columns if c]
    return unique_columns

# ============================================================================
# SIMPLE TABLE PARSER
# ============================================================================

def parse_simple_table(lines: list) -> Tuple[Optional[pd.DataFrame], Optional[float]]:
    
    logger.info("Parsing simple table format")
    
    # Find header line (contains "Freq" and "Mag" or "Phase")
    header_idx = -1
    for i, line in enumerate(lines):
        if re.search(r'freq.*hz', line, re.IGNORECASE):
            header_idx = i
            break
    
    if header_idx == -1:
        st.error("Could not find header line with frequency column")
        return None, None
    
    # Find data start (skip separator lines with ===)
    data_start_idx = header_idx + 1
    while data_start_idx < len(lines):
        if '=' in lines[data_start_idx] or not lines[data_start_idx].strip():
            data_start_idx += 1
        else:
            break
    
    # Parse header to get column names
    header_line = lines[header_idx]
    # Split by tabs or multiple spaces
    header_parts = re.split(r'\t+|\s{2,}', header_line.strip())
    header_parts = [h.strip() for h in header_parts if h.strip()]
    
    logger.info(f"Found columns: {header_parts}")
    
    # Read data - handle both comma and dot decimal separators
    data_rows = []
    for line in lines[data_start_idx:]:
        line = line.strip()
        if not line or '=' in line:  # Skip empty lines and separators
            continue
        
        # Replace comma with dot for decimals, then split by tabs or multiple spaces
        line_normalized = line.replace(',', '.')
        values = re.split(r'\t+|\s{2,}', line_normalized)
        values = [v.strip() for v in values if v.strip()]
        
        if len(values) >= len(header_parts):
            data_rows.append(values[:len(header_parts)])
    
    if not data_rows:
        st.error("No data rows found in file")
        return None, None
    
    # Create DataFrame
    df = pd.DataFrame(data_rows, columns=header_parts)
    
    # Convert to numeric
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    
    # Standardize column names for consistency
    column_mapping = {}
    for col in df.columns:
        col_lower = col.lower()
        if 'freq' in col_lower:
            column_mapping[col] = 'Frequency[Hz]'
        elif 'mag' in col_lower and 'ratio' in col_lower:
            column_mapping[col] = 'Chan-1 Magnitude[ratio]'
        elif 'phase' in col_lower and 'rad' in col_lower:
            column_mapping[col] = 'Chan-1 Phase_Shift[rad]'
    
    df.rename(columns=column_mapping, inplace=True)
    
    # Add Loop column (simple format typically has only one measurement)
    df['Loop'] = '1'
    
    logger.info(f"Parsed {len(df)} rows with columns: {df.columns.tolist()}")
    
    # No reference resistor in simple format
    return df, DEFAULT_REF_RESISTOR


# ============================================================================
# OE PSIP PARSER
# ============================================================================

def find_header_end(lines: list) -> int:
    last_marker_idx = -1
    for i, line in enumerate(lines):
        if HEADER_MARKER in line:
            last_marker_idx = i
    return last_marker_idx


def extract_resistor_value(lines: list) -> Tuple[float, bool]:
    """Extract reference resistor value from file metadata."""
    for line in lines:
        if RESISTOR_KEY in line:
            try:
                value = float(line.split(',')[1])
                logger.info(f"Found reference resistor: {value} Ohms")
                return value, True
            except (IndexError, ValueError) as e:
                logger.warning(f"Failed to parse resistor value: {e}")
    
    logger.warning(f"Resistor value not found, using default: {DEFAULT_REF_RESISTOR} Ohms")
    return DEFAULT_REF_RESISTOR, False


def build_column_headers(channel_line: str, column_line: str) -> list:
    """Build combined column headers from channel and column name lines."""
    channel_tokens = channel_line.strip().split(',')
    col_tokens = column_line.strip().split(',')
    
    # Align lengths by padding with empty strings
    max_len = max(len(channel_tokens), len(col_tokens))
    channel_tokens += [''] * (max_len - len(channel_tokens))
    col_tokens += [''] * (max_len - len(col_tokens))
    
    # Merge Channel + Column Name (e.g., "Chan-3 Magnitude[ratio]")
    unique_columns = []
    for ch, col in zip(channel_tokens, col_tokens):
        col = col.strip()
        ch = ch.strip()
        if ch:
            unique_columns.append(f"{ch} {col}")
        else:
            unique_columns.append(col)
    
    # Remove empty column names (caused by trailing commas)
    unique_columns = [c for c in unique_columns if c]
    
    return unique_columns


def parse_oe_psip_format(lines: list) -> Tuple[Optional[pd.DataFrame], Optional[float]]:
    """Parse O&E PSIP format files (like H3_Almyros.csv).
    
    Args:
        lines: List of file lines
        
    Returns:
        Tuple of (DataFrame, resistor_value)
    """
    logger.info("Parsing O&E PSIP format")
    
    # Find header end marker
    header_end_index = find_header_end(lines)
    if header_end_index == -1:
        st.error(f"Could not find '{HEADER_MARKER}' marker in file. "
                "This may not be a valid O&E PSIP file.")
        return None, None
    
    # Extract reference resistor value
    ref_resistor, resistor_found = extract_resistor_value(lines)
    if not resistor_found:
        st.warning(f"Could not find resistor value in file. Using default {DEFAULT_REF_RESISTOR} Ohms")
    
    # Identify key line positions
    channel_line_idx = header_end_index + 1
    col_name_line_idx = header_end_index + 2
    data_start_idx = header_end_index + 3
    
    # Build column headers
    if channel_line_idx >= len(lines) or col_name_line_idx >= len(lines):
        st.error("File structure is incomplete. Missing channel or column name lines.")
        return None, None
    
    unique_columns = build_column_headers(
        lines[channel_line_idx],
        lines[col_name_line_idx]
    )
    
    # Check data consistency - trim headers if needed
    if data_start_idx < len(lines):
        first_data_line = lines[data_start_idx].strip().split(',')
        num_data_cols = len(first_data_line)  # Count all values including empty ones
        
        logger.info(f"Headers: {len(unique_columns)} columns, Data: {num_data_cols} columns")
        
        # If data has fewer columns than headers, trim headers
        if num_data_cols < len(unique_columns):
            logger.warning(f"Trimming headers from {len(unique_columns)} to {num_data_cols}")
            unique_columns = unique_columns[:num_data_cols]
    
    # Load data section
    stringio = io.StringIO('\n'.join(lines))
    try:
        df = pd.read_csv(
            stringio,
            skiprows=data_start_idx,
            header=None,
            names=unique_columns,
            usecols=range(len(unique_columns))
        )
    except Exception as e:
        st.error(f"Error reading CSV data: {e}")
        logger.error(f"CSV parsing error: {e}")
        return None, None
    
    # Convert numeric columns to proper types
    # Skip columns that should remain as strings (Loop, Comment, etc.)
    skip_columns = ['Loop', 'Comment', 'User_Comment']
    
    for col in df.columns:
        if col not in skip_columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    logger.info(f"Parsed {len(df)} rows, {len(df.columns)} columns")
    return df, ref_resistor


# ============================================================================
# UNIFIED PARSER
# ============================================================================

def validate_dataframe(df: pd.DataFrame) -> bool:
    """Validate that the parsed dataframe contains expected SIP data."""
    if df.empty:
        st.error('No valid data rows found in file. The file may be empty or corrupted.')
        return False
    
    # Check for Frequency column (required) - case insensitive
    freq_cols = [col for col in df.columns if 'frequency' in str(col).lower()]
    if not freq_cols:
        st.error(f'No Frequency column found. Available columns: {df.columns.tolist()[:10]}')
        return False
    
    # Check for at least one Magnitude or Phase column
    has_mag = any('magnitude' in str(col).lower() for col in df.columns)
    has_phase = any('phase' in str(col).lower() for col in df.columns)
    
    if not (has_mag or has_phase):
        st.warning('No Magnitude or Phase columns found. Data visualization only (no physics calculations).')
    
    logger.info(f"Validated dataframe: {len(df)} rows, {len(df.columns)} columns")
    return True


@st.cache_data
def parse_sip_file(uploaded_file) -> Tuple[Optional[pd.DataFrame], Optional[float], Optional[str]]:
    """Parse SIP file with automatic format detection.
    
    Args:
        uploaded_file: Streamlit uploaded file object
        
    Returns:
        Tuple of (DataFrame with parsed data, reference resistor value, format type)
        Returns (None, None, None) if parsing fails
    """
    # Read file content
    try:
        stringio = io.StringIO(uploaded_file.getvalue().decode("utf-8"))
    except UnicodeDecodeError:
        try:
            stringio = io.StringIO(uploaded_file.getvalue().decode("latin-1"))
        except Exception as e:
            st.error(
                "Unable to decode file. The file may be corrupted or not a valid text-based file. "
                "Try opening it in a text editor to verify the format."
            )
            logger.error(f"File decoding failed: {e}")
            return None, None, None
    
    lines = stringio.readlines()
    
    if not lines:
        st.error("File is empty")
        return None, None, None
    
    # Detect file format
    file_format = detect_file_format(lines)
    
    # Parse based on detected format
    if file_format == FileFormat.OE_PSIP:
        df, ref_resistor = parse_oe_psip_format(lines)
        format_name = "O&E PSIP Format"
    elif file_format == FileFormat.SIMPLE_TABLE:
        df, ref_resistor = parse_simple_table(lines)
        format_name = "Simple Table Format"
    else:
        st.error(
            "Unknown file format. Supported formats:\n"
            "- O&E PSIP files (with ***End_Of_Header*** marker)\n"
            "- Simple table files (Freq/Magnitude/Phase columns)"
        )
        return None, None, None
    
    if df is None:
        return None, None, None
    
    # Validate the parsed data
    if not validate_dataframe(df):
        return None, None, None
    
    logger.info(f"Successfully parsed file as {format_name}")
    return df, ref_resistor, format_name


# ============================================================================
# PHYSICS CALCULATIONS
# ============================================================================

def calculate_physics_properties(
    sip_data: pd.DataFrame,
    reference_resistor: float,
    sample_length: float,
    sample_area: float
) -> pd.DataFrame:
    """Calculate resistance, resistivity, and conductivity for all channels.
    
    Uses formulas according the Excel worksheet:
    - Resistance = Magnitude × Reference Resistor
    - Resistivity = (Resistance × Area) / Length
    - Fluid Conductivity = (1 / Resistivity) × 10000 (μS/cm)
    - Real Conductivity = (1 / Resistivity) × cos(Phase) (S/m)
    - Imaginary Conductivity = -(1 / Resistivity) × sin(Phase) (S/m)
    - Cell Constant K = 1,000,000 × 0.1606 / Resistance
    - Phase in milliradians = -Phase × 1000
    
    Args:
        sip_data: DataFrame with raw SIP data
        reference_resistor: Reference resistor value in Ohms
        sample_length: Sample length in meters
        sample_area: Sample cross-sectional area in square meters
        
    Returns:
        DataFrame with calculated properties added
    """
    # Find all Magnitude columns to calculate physics for each channel
    magnitude_columns = [c for c in sip_data.columns if 'Magnitude[ratio]' in c]
    
    if not magnitude_columns:
        logger.warning("No magnitude columns found for calculations")
        st.info("No Magnitude[ratio] columns found. Skipping physics calculations. "
               "The file may only contain frequency sweep data.")
        return sip_data
    
    logger.info(f"Calculating physics properties for {len(magnitude_columns)} channels")
    
    
    for mag_col in magnitude_columns:
        # Extract prefix (e.g., "Chan-1")
        prefix = mag_col.replace(' Magnitude[ratio]', '')
        
        # Find corresponding Phase column
        phase_col = f"{prefix} Phase_Shift[rad]"
        has_phase = phase_col in sip_data.columns
        
        # D: Resistance (Ω) = Magnitude × Reference Resistor
        resistance_col = f"{prefix} Resistance (Ohms)"
        sip_data[resistance_col] = sip_data[mag_col] * reference_resistor
        
        # E: Resistivity (Ω·m) = (Resistance × Area) / Length
        resistivity_col = f"{prefix} Resistivity (Ohm-m)"
        sip_data[resistivity_col] = (sip_data[resistance_col] * sample_area) / sample_length
        
        # F: Fluid Conductivity (μS/cm) = (1 / Resistivity) × 10000
        fluid_cond_col = f"{prefix} Fluid Conductivity (uS/cm)"
        sip_data[fluid_cond_col] = np.where(
            sip_data[resistivity_col] > MIN_RESISTIVITY_THRESHOLD,
            (1 / sip_data[resistivity_col]) * 10000,
            np.nan
        )
        
        # J: Cell Constant K = 1,000,000 × 0.1606 / Resistance
        k_col = f"{prefix} Cell Constant K"
        sip_data[k_col] = np.where(
            sip_data[resistance_col] > 1e-10,
            1000000 * CELL_CONSTANT_FACTOR / sip_data[resistance_col],
            np.nan
        )
        
        # Phase-dependent calculations (only if phase data available)
        if has_phase:
            # G: Phase in milliradians = -Phase × 1000
            phase_mrad_col = f"{prefix} Phase (mRads)"
            sip_data[phase_mrad_col] = -sip_data[phase_col] * 1000
            
            # H: Imaginary Conductivity (S/m) = -(1 / Resistivity) × sin(Phase)
            imag_cond_col = f"{prefix} Imaginary Conductivity (S/m)"
            sip_data[imag_cond_col] = np.where(
                sip_data[resistivity_col] > MIN_RESISTIVITY_THRESHOLD,
                -(1 / sip_data[resistivity_col]) * np.sin(sip_data[phase_col]),
                np.nan
            )
            
            # I: Real Conductivity (S/m) = (1 / Resistivity) × cos(Phase)
            real_cond_col = f"{prefix} Real Conductivity (S/m)"
            sip_data[real_cond_col] = np.where(
                sip_data[resistivity_col] > MIN_RESISTIVITY_THRESHOLD,
                (1 / sip_data[resistivity_col]) * np.cos(sip_data[phase_col]),
                np.nan
            )
            
            # K: Imaginary Conductivity in μS/cm = Imaginary Conductivity × 10000
            imag_cond_uscm_col = f"{prefix} Imaginary Conductivity (uS/cm)"
            sip_data[imag_cond_uscm_col] = sip_data[imag_cond_col] * 10000
    
    return sip_data
# ============================================================================
#COMPARISON PLOT BUILDER
# ============================================================================
def create_comparison_plot(datasets: Dict[str, pd.DataFrame], x_col: str, y_col: str,
                          log_x: bool = False, log_y: bool = False,
                          plot_type: str = 'overlay',
                          selected_loops: Dict[str, List[str]] = None,
                          color_map: Dict[str, str] = None,
                          custom_title: str = None,
                          custom_x_label: str = None,
                          custom_y_label: str = None) -> go.Figure:
    """Create comparison plot with manual color support and editable titles."""
    if custom_title is None:
        custom_title = f"{y_col} vs {x_col}"
    if custom_x_label is None:
        custom_x_label = x_col
    if custom_y_label is None:
        custom_y_label = y_col
 
    if plot_type == 'overlay':
        fig = go.Figure()
        for name, df in datasets.items():
            if x_col in df.columns and y_col in df.columns:
                if selected_loops and name in selected_loops and 'Loop' in df.columns:
                    if selected_loops[name]:
                        df = df[df['Loop'].isin(selected_loops[name])]
                if df.empty: continue
                line_color = color_map.get(name) if color_map else None
                if 'Loop' in df.columns and len(df['Loop'].unique()) > 1:
                    for loop in sorted(df['Loop'].unique()):
                        loop_data = df[df['Loop'] == loop]
                        fig.add_trace(go.Scatter(
                            x=loop_data[x_col], y=loop_data[y_col],
                            mode='lines+markers', name=f"{name} - L{loop}",
                            line=dict(color=line_color), marker=dict(size=6)
                        ))
                else:
                    fig.add_trace(go.Scatter(
                        x=df[x_col], y=df[y_col],
                        mode='lines+markers', name=name,
                        line=dict(color=line_color), marker=dict(size=6)
                    ))
        fig.update_layout(
            title=dict(text=custom_title, x=0.5, xanchor='center', font=dict(size=16)),
            xaxis_title=custom_x_label, yaxis_title=custom_y_label
        )
 
    elif plot_type == 'subplots':
        n_datasets = len(datasets)
        fig = make_subplots(
            rows=n_datasets, cols=1,
            subplot_titles=list(datasets.keys()),
            vertical_spacing=0.15 / n_datasets if n_datasets > 1 else 0.1
        )
        for idx, (name, df) in enumerate(datasets.items(), 1):
            if x_col in df.columns and y_col in df.columns:
                if selected_loops and name in selected_loops and 'Loop' in df.columns:
                    if selected_loops[name]:
                        df = df[df['Loop'].isin(selected_loops[name])]
                if df.empty: continue
                line_color = color_map.get(name) if color_map else None
                if 'Loop' in df.columns and len(df['Loop'].unique()) > 1:
                    for loop in sorted(df['Loop'].unique()):
                        loop_data = df[df['Loop'] == loop]
                        fig.add_trace(
                            go.Scatter(
                                x=loop_data[x_col], y=loop_data[y_col],
                                mode='lines+markers', name=f"Loop {loop}",
                                line=dict(color=line_color), marker=dict(size=6),
                                legendgroup=f"file{idx}", legendgrouptitle_text=name
                            ), row=idx, col=1
                        )
                else:
                    fig.add_trace(go.Scatter(
                        x=df[x_col], y=df[y_col],
                        mode='lines+markers', name=name,
                        line=dict(color=line_color), marker=dict(size=6)
                    ), row=idx, col=1)
        fig.update_layout(
            title=dict(text=custom_title, x=0.5, xanchor='center', font=dict(size=16))
        )
        for idx in range(1, n_datasets + 1):
            fig.update_xaxes(title_text=custom_x_label, row=idx, col=1)
            fig.update_yaxes(title_text=custom_y_label, row=idx, col=1)
 
    fig.update_xaxes(type='log' if log_x else 'linear')
    fig.update_yaxes(type='log' if log_y else 'linear')
    fig.update_layout(
        height=600 if plot_type == 'overlay' else 500 * len(datasets)
    )
    return fig
# ============================================================================
#PLOT CONFIGURATION HELPER
# ============================================================================
def get_plot_config():
    """Return Plotly config wit editability enabled."""
    return {
        'editable': True,
        'toImageButtonOptions': {
            'format': 'png',
            'filename': 'sip_plot',
            'height': 1200,
            'width': 1600,
            'scale': 2
        },
        'displaylogo': False,
        'modeBarButtonsToAdd': [
            'drawline', 'drawopenpath', 'drawclosedpath', 'drawcircle', 'drawrect', 'eraseshape'
        ],
        'modeBarButtonsToRemove': []
    }


def get_line_color_customization(traces, key_prefix=""):
    """Create UI for individual line color customization.
    
    Args:
        traces: List of trace names/identifiers
        key_prefix: Prefix for widget keys
        
    Returns:
        Dictionary mapping trace names to colors
    """
    st.markdown("**🎨 Individual Line Colors:**")
    
    # Default color palette
    default_colors = [
        '#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A',
        '#19D3F3', '#FF6692', '#B6E880', '#FF97FF', '#FECB52'
    ]
    
    color_map = {}
    
    # Create color pickers for each trace
    for idx, trace_name in enumerate(traces):
        default_color = default_colors[idx % len(default_colors)]
        color = st.color_picker(
            f"Line {idx + 1}: {trace_name[:30]}",
            value=default_color,
            key=f"{key_prefix}_line_{idx}"
        )
        color_map[trace_name] = color
    
    return color_map


def get_plot_style_customization(key_prefix=""):
    """Create UI for plot style customization.
    
    Args:
        key_prefix: Prefix for widget keys
        
    Returns:
        Dictionary with style settings
    """
    st.markdown("**🎨 Plot Style:**")
    
    with st.expander("📊 Background Colors"):
        col1, col2 = st.columns(2)
        with col1:
            plot_bg = st.color_picker(
                "Plot Background",
                value="#000000",
                help="Background inside plot area",
                key=f"{key_prefix}_plot_bg"
            )
        with col2:
            paper_bg = st.color_picker(
                "Paper Background",
                value="#000000",
                help="Background outside plot area",
                key=f"{key_prefix}_paper_bg"
            )
    
    with st.expander("✏️ Text Colors"):
        col1, col2, col3 = st.columns(3)
        with col1:
            title_color = st.color_picker(
                "Title",
                value="#FFFFFF",
                key=f"{key_prefix}_title_color"
            )
        with col2:
            axis_color = st.color_picker(
                "Axis Labels",
                value="#FFFFFF",
                key=f"{key_prefix}_axis_color"
            )
        with col3:
            legend_color = st.color_picker(
                "Legend",
                value="#FFFFFF",
                key=f"{key_prefix}_legend_color"
            )
    
    with st.expander("📐 Grid & Lines"):
        col1, col2 = st.columns(2)
        with col1:
            grid_color = st.color_picker(
                "Grid Color",
                value="#808080",
                key=f"{key_prefix}_grid"
            )
            grid_opacity = st.slider(
                "Grid Opacity",
                0.0, 1.0, 0.3, 0.1,
                key=f"{key_prefix}_grid_opacity"
            )
        with col2:
            zeroline_color = st.color_picker(
                "Zero Line",
                value="#808080",
                key=f"{key_prefix}_zeroline"
            )
            zeroline_opacity = st.slider(
                "Zero Line Opacity",
                0.0, 1.0, 0.5, 0.1,
                key=f"{key_prefix}_zeroline_opacity"
            )
    
    with st.expander("📦 Legend Style"):
        col1, col2 = st.columns(2)
        with col1:
            legend_bg = st.color_picker(
                "Background",
                value="#000000",
                key=f"{key_prefix}_legend_bg"
            )
            legend_bg_opacity = st.slider(
                "BG Opacity",
                0.0, 1.0, 0.8, 0.1,
                key=f"{key_prefix}_legend_bg_opacity"
            )
        with col2:
            legend_border = st.color_picker(
                "Border",
                value="#FFFFFF",
                key=f"{key_prefix}_legend_border"
            )
            legend_border_width = st.slider(
                "Border Width",
                0, 5, 1,
                key=f"{key_prefix}_legend_border_width"
            )
    
    with st.expander("📏 Line Settings"):
        col1, col2 = st.columns(2)
        with col1:
            line_width = st.slider(
                "Line Width",
                1, 8, 2,
                key=f"{key_prefix}_line_width"
            )
        with col2:
            marker_size = st.slider(
                "Marker Size",
                2, 16, 6,
                key=f"{key_prefix}_marker_size"
            )
    
    return {
        'plot_bgcolor': plot_bg,
        'paper_bgcolor': paper_bg,
        'title_color': title_color,
        'axis_color': axis_color,
        'legend_text_color': legend_color,
        'grid_color': grid_color,
        'grid_opacity': grid_opacity,
        'zeroline_color': zeroline_color,
        'zeroline_opacity': zeroline_opacity,
        'legend_bgcolor': legend_bg,
        'legend_bg_opacity': legend_bg_opacity,
        'legend_border_color': legend_border,
        'legend_border_width': legend_border_width,
        'line_width': line_width,
        'marker_size': marker_size
    }


def apply_style_to_figure(fig, style_config, line_colors=None, font_config=None, legend_config=None):
    """Apply style customizations to a Plotly figure.
    
    Args:
        fig: Plotly figure object
        style_config: Dictionary with style settings
        line_colors: Optional dictionary mapping trace names to colors
        font_config: Optional dictionary with font sizes
        legend_config: Optional dictionary with legend settings
    """
    def hex_to_rgba(hex_color, opacity=1.0):
        hex_color = hex_color.lstrip('#')
        r, g, b = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
        return f'rgba({r},{g},{b},{opacity})'
    
    grid_rgba = hex_to_rgba(style_config['grid_color'], style_config['grid_opacity'])
    zeroline_rgba = hex_to_rgba(style_config['zeroline_color'], style_config['zeroline_opacity'])
    legend_bg_rgba = hex_to_rgba(style_config['legend_bgcolor'], style_config['legend_bg_opacity'])
    
    # Default font sizes if not provided
    if font_config is None:
        font_config = {
            'title_size': 16,
            'axis_label_size': 12,
            'tick_size': 10,
            'legend_size': 10
        }
    
    # Default legend config if not provided
    if legend_config is None:
        legend_config = {
            'show': True,
            'title': '',
            'orientation': 'vertical',
            'x': 0.01,
            'y': 0.99,
            'xanchor': 'left',
            'yanchor': 'top'
        }
    
    # Build legend dict
    legend_dict = {
        'bgcolor': legend_bg_rgba,
        'bordercolor': style_config['legend_border_color'],
        'borderwidth': style_config['legend_border_width'],
        'font': dict(
            color=style_config['legend_text_color'],
            size=font_config['legend_size']
        ),
        'orientation': legend_config['orientation'],
        'x': legend_config['x'],
        'y': legend_config['y'],
        'xanchor': legend_config['xanchor'],
        'yanchor': legend_config['yanchor']
    }
    
    if legend_config.get('title'):
        legend_dict['title'] = dict(
            text=legend_config['title'],
            font=dict(size=font_config['legend_size'] + 2)
        )
    
    fig.update_layout(
        paper_bgcolor=style_config['paper_bgcolor'],
        plot_bgcolor=style_config['plot_bgcolor'],
        font=dict(
            color=style_config['axis_color'],
            size=font_config['tick_size']
        ),
        title=dict(
            font=dict(
                color=style_config['title_color'],
                size=font_config['title_size']
            )
        ),
        xaxis=dict(
            gridcolor=grid_rgba,
            zerolinecolor=zeroline_rgba,
            color=style_config['axis_color'],
            title=dict(font=dict(size=font_config['axis_label_size'])),
            tickfont=dict(size=font_config['tick_size'])
        ),
        yaxis=dict(
            gridcolor=grid_rgba,
            zerolinecolor=zeroline_rgba,
            color=style_config['axis_color'],
            title=dict(font=dict(size=font_config['axis_label_size'])),
            tickfont=dict(size=font_config['tick_size'])
        ),
        legend=legend_dict,
        showlegend=legend_config['show']
    )
    
    # Apply line colors and settings
    if line_colors:
        for trace in fig.data:
            trace_name = trace.name
            if trace_name in line_colors:
                trace.update(
                    line=dict(
                        color=line_colors[trace_name],
                        width=style_config['line_width']
                    ),
                    marker=dict(
                        size=style_config['marker_size'],
                        color=line_colors[trace_name]
                    )
                )
    else:
        # Apply default line settings
        fig.update_traces(
            line=dict(width=style_config['line_width']),
            marker=dict(size=style_config['marker_size'])
        )
    
    return fig

#WIP - PRESETS
def get_research_presets():
    """Return dictionary of research paper quality presets.
    
    Returns:
        Dictionary with preset configurations
    """
    return {
        "Nature/Science": {
            'plot_bgcolor': '#FFFFFF',
            'paper_bgcolor': '#FFFFFF',
            'title_color': '#000000',
            'axis_color': '#000000',
            'legend_text_color': '#000000',
            'grid_color': '#E5E5E5',
            'grid_opacity': 0.5,
            'zeroline_color': '#000000',
            'zeroline_opacity': 0.8,
            'legend_bgcolor': '#FFFFFF',
            'legend_bg_opacity': 0.9,
            'legend_border_color': '#000000',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 4,
            'description': 'Clean white background, minimal styling'
        },
        "ACS Journals": {
            'plot_bgcolor': '#FFFFFF',
            'paper_bgcolor': '#FFFFFF',
            'title_color': '#000000',
            'axis_color': '#000000',
            'legend_text_color': '#000000',
            'grid_color': '#CCCCCC',
            'grid_opacity': 0.3,
            'zeroline_color': '#000000',
            'zeroline_opacity': 0.7,
            'legend_bgcolor': '#FFFFFF',
            'legend_bg_opacity': 1.0,
            'legend_border_color': '#000000',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 6,
            'description': 'Professional, high contrast'
        },
        "IEEE": {
            'plot_bgcolor': '#FFFFFF',
            'paper_bgcolor': '#FFFFFF',
            'title_color': '#000000',
            'axis_color': '#000000',
            'legend_text_color': '#000000',
            'grid_color': '#D3D3D3',
            'grid_opacity': 0.4,
            'zeroline_color': '#000000',
            'zeroline_opacity': 0.8,
            'legend_bgcolor': '#FAFAFA',
            'legend_bg_opacity': 1.0,
            'legend_border_color': '#666666',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 5,
            'description': 'Technical, subtle grid'
        },
        "Elsevier": {
            'plot_bgcolor': '#FFFFFF',
            'paper_bgcolor': '#FFFFFF',
            'title_color': '#000000',
            'axis_color': '#000000',
            'legend_text_color': '#000000',
            'grid_color': '#E0E0E0',
            'grid_opacity': 0.5,
            'zeroline_color': '#333333',
            'zeroline_opacity': 0.7,
            'legend_bgcolor': '#FFFFFF',
            'legend_bg_opacity': 0.95,
            'legend_border_color': '#999999',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 5,
            'description': 'Standard publication style'
        },
        "Presentation": {
            'plot_bgcolor': '#000000',
            'paper_bgcolor': '#000000',
            'title_color': '#FFFFFF',
            'axis_color': '#FFFFFF',
            'legend_text_color': '#FFFFFF',
            'grid_color': '#808080',
            'grid_opacity': 0.4,
            'zeroline_color': '#FFFFFF',
            'zeroline_opacity': 0.6,
            'legend_bgcolor': '#000000',
            'legend_bg_opacity': 0.8,
            'legend_border_color': '#FFFFFF',
            'legend_border_width': 2,
            'line_width': 3,
            'marker_size': 8,
            'description': 'Dark theme, high visibility'
        },
        "Grayscale Print": {
            'plot_bgcolor': '#FFFFFF',
            'paper_bgcolor': '#FFFFFF',
            'title_color': '#000000',
            'axis_color': '#000000',
            'legend_text_color': '#000000',
            'grid_color': '#CCCCCC',
            'grid_opacity': 0.3,
            'zeroline_color': '#000000',
            'zeroline_opacity': 0.8,
            'legend_bgcolor': '#F5F5F5',
            'legend_bg_opacity': 1.0,
            'legend_border_color': '#000000',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 6,
            'description': 'Optimized for B&W printing'
        }
    }


def get_colorblind_safe_palette():
    """Return colorblind-safe color palette.
    
    Returns:
        List of hex colors
    """
    return [
        '#0173B2',  # Blue
        '#DE8F05',  # Orange
        '#029E73',  # Green
        '#CC78BC',  # Purple
        '#CA9161',  # Brown
        '#949494',  # Gray
        '#ECE133',  # Yellow
        '#56B4E9'   # Sky Blue
    ]


def get_export_ui(fig, key_prefix=""):
    """Create advanced export UI with dimension and format options.
    
    Args:
        fig: Plotly figure to export
        key_prefix: Prefix for widget keys
        
    Returns:
        None (handles export internally)
    """
    st.markdown("---")
    st.markdown("### 📥 Export Plot")
    
    with st.expander("Export Settings", expanded=True):
        # Export format
        export_format = st.selectbox(
            "File Format",
            options=['PNG', 'SVG', 'PDF', 'JPEG'],
            help="PNG: Raster, best for most uses | SVG: Vector, scalable | PDF: Vector, publications | JPEG: Compressed",
            key=f"{key_prefix}_export_format"
        )
        
        # Preset dimensions
        col1, col2 = st.columns(2)
        with col1:
            preset = st.selectbox(
                "Dimension Preset",
                options=[
                    'Custom',
                    'Publication Single Column (3.5" × 2.5")',
                    'Publication Double Column (7" × 5")',
                    'Publication Full Page (8.5" × 6.5")',
                    'Presentation 16:9 (1920 × 1080)',
                    'Presentation 4:3 (1600 × 1200)',
                    'Poster (3600 × 2700)',
                    'Screen HD (1280 × 720)',
                    'Screen Full HD (1920 × 1440)',
                    'Ultra HD (3840 × 2160)'
                ],
                key=f"{key_prefix}_preset"
            )
        
        # Dimension mapping
        preset_dims = {
            'Custom': (1600, 1200),
            'Publication Single Column (3.5" × 2.5")': (1050, 750),
            'Publication Double Column (7" × 5")': (2100, 1500),
            'Publication Full Page (8.5" × 6.5")': (2550, 1950),
            'Presentation 16:9 (1920 × 1080)': (1920, 1080),
            'Presentation 4:3 (1600 × 1200)': (1600, 1200),
            'Poster (3600 × 2700)': (3600, 2700),
            'Screen HD (1280 × 720)': (1280, 720),
            'Screen Full HD (1920 × 1440)': (1920, 1440),
            'Ultra HD (3840 × 2160)': (3840, 2160)
        }
        
        default_width, default_height = preset_dims.get(preset, (1600, 1200))
        
        with col2:
            dpi = st.selectbox(
                "DPI / Quality",
                options=[72, 150, 300, 600],
                index=2,
                help="72: Screen | 150: Draft print | 300: Publication | 600: High quality",
                key=f"{key_prefix}_dpi"
            )
        
        # Custom dimensions
        if preset == 'Custom':
            col1, col2 = st.columns(2)
            with col1:
                width = st.number_input(
                    "Width (pixels)",
                    min_value=400,
                    max_value=10000,
                    value=default_width,
                    step=100,
                    key=f"{key_prefix}_width"
                )
            with col2:
                height = st.number_input(
                    "Height (pixels)",
                    min_value=300,
                    max_value=10000,
                    value=default_height,
                    step=100,
                    key=f"{key_prefix}_height"
                )
        else:
            width = default_width
            height = default_height
            st.info(f"Dimensions: {width} × {height} pixels")
        
        # Scale factor
        scale = st.slider(
            "Scale Factor",
            min_value=1,
            max_value=4,
            value=2,
            help="Higher scale = better quality, larger file. 2× is standard.",
            key=f"{key_prefix}_scale"
        )
        
        # File name
        filename = st.text_input(
            "Filename",
            value=f"sip_plot.{export_format.lower()}",
            key=f"{key_prefix}_filename"
        )
        
        # Calculate file info
        estimated_size = (width * height * scale * scale * 3) / (1024 * 1024)  # Rough estimate
        st.caption(f"Estimated size: ~{estimated_size:.1f} MB | Final: {width * scale} × {height * scale} pixels")
        
        # Export button
        if st.button("📥 Export Plot", type="primary", key=f"{key_prefix}_export_btn"):
            try:
                # Update figure size
                fig.update_layout(
                    width=width,
                    height=height
                )
                
                # Export based on format
                if export_format == 'PNG':
                    img_bytes = fig.to_image(
                        format='png',
                        width=width,
                        height=height,
                        scale=scale
                    )
                    mime_type = 'image/png'
                elif export_format == 'JPEG':
                    img_bytes = fig.to_image(
                        format='jpeg',
                        width=width,
                        height=height,
                        scale=scale
                    )
                    mime_type = 'image/jpeg'
                elif export_format == 'SVG':
                    img_bytes = fig.to_image(
                        format='svg',
                        width=width,
                        height=height
                    )
                    mime_type = 'image/svg+xml'
                elif export_format == 'PDF':
                    img_bytes = fig.to_image(
                        format='pdf',
                        width=width,
                        height=height
                    )
                    mime_type = 'application/pdf'
                
                # Provide download button
                st.download_button(
                    label=f"⬇️ Download {export_format}",
                    data=img_bytes,
                    file_name=filename,
                    mime=mime_type,
                    key=f"{key_prefix}_download"
                )
                
                st.success(f"✅ Plot exported successfully! Click 'Download {export_format}' above.")
                
            except Exception as e:
                st.error(f"Export failed: {str(e)}")
                st.info("💡 Tip: Try installing kaleido: `pip install kaleido`")


def get_research_customization_ui(key_prefix=""):
    """Create research-paper level customization UI with presets, fonts, and legend control.
    
    Args:
        key_prefix: Prefix for widget keys
        
    Returns:
        Tuple of (style_config, use_colorblind, font_config, legend_config)
    """
    st.markdown("---")
    st.markdown("**🎓 Research Paper Customization:**")
    
    # Preset selection
    presets = get_research_presets()
    preset_names = list(presets.keys())
    
    selected_preset = st.selectbox(
        "📋 Style Preset",
        options=['Custom'] + preset_names,
        help="Choose a journal-specific preset or custom",
        key=f"{key_prefix}_preset_select"
    )
    
    # Initialize style_config
    if selected_preset != 'Custom':
        st.caption(f"ℹ️ {presets[selected_preset]['description']}")
        
        # Load preset values
        preset_config = presets[selected_preset].copy()
        preset_config.pop('description', None)
        
        # Show preset values but allow override
        override = st.checkbox("Override preset values", value=False, key=f"{key_prefix}_override")
        
        if override:
            # Get custom values but initialize with preset defaults
            style_config = get_plot_style_customization_with_defaults(key_prefix, preset_config)
        else:
            style_config = preset_config
    else:
        # Full custom mode
        default_config = {
            'plot_bgcolor': '#000000',
            'paper_bgcolor': '#000000',
            'title_color': '#FFFFFF',
            'axis_color': '#FFFFFF',
            'legend_text_color': '#FFFFFF',
            'grid_color': '#808080',
            'grid_opacity': 0.3,
            'zeroline_color': '#808080',
            'zeroline_opacity': 0.5,
            'legend_bgcolor': '#000000',
            'legend_bg_opacity': 0.8,
            'legend_border_color': '#FFFFFF',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 6
        }
        style_config = get_plot_style_customization_with_defaults(key_prefix, default_config)
    
    # Font customization
    st.markdown("---")
    with st.expander("🔤 Font Sizes", expanded=False):
        col1, col2, col3 = st.columns(3)
        with col1:
            title_size = st.slider(
                "Title",
                min_value=10,
                max_value=32,
                value=16,
                key=f"{key_prefix}_title_size"
            )
        with col2:
            axis_label_size = st.slider(
                "Axis Labels",
                min_value=8,
                max_value=24,
                value=12,
                key=f"{key_prefix}_axis_label_size"
            )
        with col3:
            tick_size = st.slider(
                "Tick Labels",
                min_value=6,
                max_value=20,
                value=10,
                key=f"{key_prefix}_tick_size"
            )
        
        legend_size = st.slider(
            "Legend Text",
            min_value=6,
            max_value=20,
            value=10,
            key=f"{key_prefix}_legend_size"
        )
    
    font_config = {
        'title_size': title_size,
        'axis_label_size': axis_label_size,
        'tick_size': tick_size,
        'legend_size': legend_size
    }
    
    # Legend editor
    st.markdown("---")
    with st.expander("📦 Legend Editor", expanded=False):
        col1, col2 = st.columns(2)
        with col1:
            legend_position = st.selectbox(
                "Position",
                options=[
                    "top-left", "top-center", "top-right",
                    "middle-left", "middle-right",
                    "bottom-left", "bottom-center", "bottom-right",
                    "outside-right"
                ],
                index=0,
                key=f"{key_prefix}_legend_pos"
            )
        with col2:
            legend_orientation = st.selectbox(
                "Orientation",
                options=["Vertical", "Horizontal"],
                index=0,
                key=f"{key_prefix}_legend_orient"
            )
        
        # Map to Plotly's expected values
        orientation_map = {
            "Vertical": "v",
            "Horizontal": "h"
        }
        plotly_orientation = orientation_map[legend_orientation]
        
        show_legend = st.checkbox(
            "Show Legend",
            value=True,
            key=f"{key_prefix}_show_legend"
        )
        
        if show_legend:
            legend_title = st.text_input(
                "Legend Title (optional)",
                value="",
                key=f"{key_prefix}_legend_title"
            )
        else:
            legend_title = ""
    
    # Map legend position to coordinates
    legend_pos_map = {
        "top-left": {"x": 0.01, "y": 0.99, "xanchor": "left", "yanchor": "top"},
        "top-center": {"x": 0.5, "y": 0.99, "xanchor": "center", "yanchor": "top"},
        "top-right": {"x": 0.99, "y": 0.99, "xanchor": "right", "yanchor": "top"},
        "middle-left": {"x": 0.01, "y": 0.5, "xanchor": "left", "yanchor": "middle"},
        "middle-right": {"x": 0.99, "y": 0.5, "xanchor": "right", "yanchor": "middle"},
        "bottom-left": {"x": 0.01, "y": 0.01, "xanchor": "left", "yanchor": "bottom"},
        "bottom-center": {"x": 0.5, "y": 0.01, "xanchor": "center", "yanchor": "bottom"},
        "bottom-right": {"x": 0.99, "y": 0.01, "xanchor": "right", "yanchor": "bottom"},
        "outside-right": {"x": 1.02, "y": 0.5, "xanchor": "left", "yanchor": "middle"}
    }
    
    legend_config = {
        'show': show_legend,
        'title': legend_title,
        'orientation': plotly_orientation,
        **legend_pos_map[legend_position]
    }
    
    # Colorblind-safe palette option
    st.markdown("---")
    use_colorblind = st.checkbox(
        "🌈 Use Colorblind-Safe Palette",
        help="Apply scientifically-validated colorblind-safe colors",
        key=f"{key_prefix}_colorblind"
    )
    
    return style_config, use_colorblind, font_config, legend_config


def get_plot_style_customization_with_defaults(key_prefix="", defaults=None):
    """Create UI for plot style customization with default values.
    
    Args:
        key_prefix: Prefix for widget keys
        defaults: Dictionary with default values
        
    Returns:
        Dictionary with style settings
    """
    if defaults is None:
        defaults = {
            'plot_bgcolor': '#000000',
            'paper_bgcolor': '#000000',
            'title_color': '#FFFFFF',
            'axis_color': '#FFFFFF',
            'legend_text_color': '#FFFFFF',
            'grid_color': '#808080',
            'grid_opacity': 0.3,
            'zeroline_color': '#808080',
            'zeroline_opacity': 0.5,
            'legend_bgcolor': '#000000',
            'legend_bg_opacity': 0.8,
            'legend_border_color': '#FFFFFF',
            'legend_border_width': 1,
            'line_width': 2,
            'marker_size': 6
        }
    
    st.markdown("**🎨 Plot Style:**")
    
    with st.expander("📊 Background Colors"):
        col1, col2 = st.columns(2)
        with col1:
            plot_bg = st.color_picker(
                "Plot Background",
                value=defaults.get('plot_bgcolor', '#000000'),
                help="Background inside plot area",
                key=f"{key_prefix}_plot_bg"
            )
        with col2:
            paper_bg = st.color_picker(
                "Paper Background",
                value=defaults.get('paper_bgcolor', '#000000'),
                help="Background outside plot area",
                key=f"{key_prefix}_paper_bg"
            )
    
    with st.expander("✏️ Text Colors"):
        col1, col2, col3 = st.columns(3)
        with col1:
            title_color = st.color_picker(
                "Title",
                value=defaults.get('title_color', '#FFFFFF'),
                key=f"{key_prefix}_title_color"
            )
        with col2:
            axis_color = st.color_picker(
                "Axis Labels",
                value=defaults.get('axis_color', '#FFFFFF'),
                key=f"{key_prefix}_axis_color"
            )
        with col3:
            legend_color = st.color_picker(
                "Legend",
                value=defaults.get('legend_text_color', '#FFFFFF'),
                key=f"{key_prefix}_legend_color"
            )
    
    with st.expander("📐 Grid & Lines"):
        col1, col2 = st.columns(2)
        with col1:
            grid_color = st.color_picker(
                "Grid Color",
                value=defaults.get('grid_color', '#808080'),
                key=f"{key_prefix}_grid"
            )
            grid_opacity = st.slider(
                "Grid Opacity",
                0.0, 1.0, 
                defaults.get('grid_opacity', 0.3), 
                0.1,
                key=f"{key_prefix}_grid_opacity"
            )
        with col2:
            zeroline_color = st.color_picker(
                "Zero Line",
                value=defaults.get('zeroline_color', '#808080'),
                key=f"{key_prefix}_zeroline"
            )
            zeroline_opacity = st.slider(
                "Zero Line Opacity",
                0.0, 1.0, 
                defaults.get('zeroline_opacity', 0.5), 
                0.1,
                key=f"{key_prefix}_zeroline_opacity"
            )
    
    with st.expander("📦 Legend Style"):
        col1, col2 = st.columns(2)
        with col1:
            legend_bg = st.color_picker(
                "Background",
                value=defaults.get('legend_bgcolor', '#000000'),
                key=f"{key_prefix}_legend_bg"
            )
            legend_bg_opacity = st.slider(
                "BG Opacity",
                0.0, 1.0, 
                defaults.get('legend_bg_opacity', 0.8), 
                0.1,
                key=f"{key_prefix}_legend_bg_opacity"
            )
        with col2:
            legend_border = st.color_picker(
                "Border",
                value=defaults.get('legend_border_color', '#FFFFFF'),
                key=f"{key_prefix}_legend_border"
            )
            legend_border_width = st.slider(
                "Border Width",
                0, 5, 
                defaults.get('legend_border_width', 1),
                key=f"{key_prefix}_legend_border_width"
            )
    
    with st.expander("📏 Line Settings"):
        col1, col2 = st.columns(2)
        with col1:
            line_width = st.slider(
                "Line Width",
                1, 8, 
                defaults.get('line_width', 2),
                key=f"{key_prefix}_line_width"
            )
        with col2:
            marker_size = st.slider(
                "Marker Size",
                2, 16, 
                defaults.get('marker_size', 6),
                key=f"{key_prefix}_marker_size"
            )
    
    return {
        'plot_bgcolor': plot_bg,
        'paper_bgcolor': paper_bg,
        'title_color': title_color,
        'axis_color': axis_color,
        'legend_text_color': legend_color,
        'grid_color': grid_color,
        'grid_opacity': grid_opacity,
        'zeroline_color': zeroline_color,
        'zeroline_opacity': zeroline_opacity,
        'legend_bgcolor': legend_bg,
        'legend_bg_opacity': legend_bg_opacity,
        'legend_border_color': legend_border,
        'legend_border_width': legend_border_width,
        'line_width': line_width,
        'marker_size': marker_size
    }


# ============================================================================
# MAIN APPLICATION
# ============================================================================

def main():
    st.title("SIP Data Analysis Tool")
 
    if 'datasets' not in st.session_state:
        st.session_state.datasets = {}
 
    with st.sidebar:
        st.header("1. Upload Data Files")
        mode = st.radio("Analysis Mode", ["Single File", "Compare Multiple Files"])
        uploaded_files = st.file_uploader(
            "Upload SIP files", type=["csv", "txt"], accept_multiple_files=True
        )
        st.header("2. Sample Properties")
        sample_length = st.number_input("Sample Length (m)", value=DEFAULT_SAMPLE_LENGTH, format="%.4f")
        sample_area = st.number_input("Sample Area (m²)", value=DEFAULT_SAMPLE_AREA, format="%.4f")
        manual_ref = st.number_input("Reference Resistor (Ohms)", value=0.0)
 
    if not uploaded_files:
        st.info("Please upload SIP file(s) to begin")
        with st.expander("About this app"):
            st.markdown("""
            **Features:**
            ### Intelligent Format Detection
            - **O&E PSIP Format**: Full instrument output with metadata, multi-channel support
            - **Simple Table Format**: Basic frequency/magnitude/phase data files
            - Automatic detection - no manual format selection needed
            
            ### Interactive Visualization
            - Multi-channel plotting with customizable axes
            - Loop filtering and comparison
            - Dual Y-axis support for comparing different parameters
            - Logarithmic scaling options
            - Hover tooltips for precise value inspection
            
            ### Robust Data Handling
            - Handles files with multiple header sections
            - European decimal format support (comma to dot conversion)
            - Flexible separator detection (tabs, spaces)
            - Empty column handling
            - Automatic data type conversion
            """)
        return
 
    # ── Process each uploaded file ──
    processed_datasets = {}
    for uploaded_file in uploaded_files:
        file_key = uploaded_file.name
        sip_data, file_ref_resistor, format_name = parse_sip_file(uploaded_file)
        if sip_data is None:
            st.error(f"Failed to parse {file_key}")
            continue
        st.success(f"Loaded: **{file_key}** ({format_name})")
        reference_resistor = manual_ref if manual_ref > 0 else file_ref_resistor
        with st.spinner(f"Calculating properties for {file_key}..."):
            sip_data = calculate_physics_properties(
                sip_data, reference_resistor, sample_length, sample_area
            )
        if 'Loop' in sip_data.columns:
            sip_data['Loop'] = sip_data['Loop'].astype(str)
        sip_data['Source_File'] = file_key
        processed_datasets[file_key] = sip_data
 
    if not processed_datasets:
        st.error("No files were successfully processed")
        return
 
    st.divider()
 
    if mode == "Single File":
        file_key = list(processed_datasets.keys())[0]
        sip_data = processed_datasets[file_key]
 
        col_info1, col_info2, col_info3 = st.columns(3)
        with col_info1:
            st.metric("Total Measurements", len(sip_data))
        with col_info2:
            if 'Loop' in sip_data.columns:
                st.metric("Measurement Loops", len(sip_data['Loop'].unique()))
            else:
                st.metric("Measurement Loops", "N/A")
        with col_info3:
            channels = [col.split()[0] for col in sip_data.columns if 'Magnitude' in col]
            st.metric("Channels", len(channels) if channels else 1)
 
        col1, col2 = st.columns([1, 3])
        with col1:
            st.subheader("Plot Settings")
            all_cols = sip_data.columns.tolist()
            default_x = next((i for i, col in enumerate(all_cols) if 'frequency' in col.lower()), 0)
            default_y = max(0, len(all_cols) - 1)
            x_axis = st.selectbox("X-Axis", options=all_cols, index=default_x)
            y_axis = st.selectbox("Y-Axis", options=all_cols, index=default_y)
            st.markdown("---")
            st.markdown("**Customize Labels:**")
            default_title = f"{y_axis} vs {x_axis}"
            custom_title = st.text_input("Plot Title", value=default_title)
            custom_x_label = st.text_input("X-Axis Label", value=x_axis)
            custom_y_label = st.text_input("Y-Axis Label", value=y_axis)
            st.markdown("---")
            if 'Loop' in sip_data.columns:
                loops = sorted(sip_data['Loop'].unique())
                selected_loops = st.multiselect("Select Loops", loops, default=loops)
                plot_data = sip_data[sip_data['Loop'].isin(selected_loops)] if len(selected_loops) < len(loops) else sip_data
            else:
                plot_data = sip_data
            log_x = st.checkbox("Log Scale X-Axis", value=True)
            log_y = st.checkbox("Log Scale Y-Axis", value=False)
            
            # Get research-level plot customization
            style_config, use_colorblind, font_config, legend_config = get_research_customization_ui("single_file")
 
        with col2:
            if plot_data.empty:
                st.warning("No data selected.")
                return
            
            # Create initial figure
            fig = px.line(
                plot_data, x=x_axis, y=y_axis,
                color='Loop' if 'Loop' in plot_data.columns else None,
                markers=True, title=custom_title, log_x=log_x, log_y=log_y
            )
            
            # Get trace names for line color customization
            trace_names = [trace.name for trace in fig.data]
            
            # Show line color pickers in sidebar (inside col1)
            with col1:
                st.markdown("---")
                if use_colorblind:
                    colorblind_palette = get_colorblind_safe_palette()
                    line_colors = {}
                    for idx, trace_name in enumerate(trace_names):
                        line_colors[trace_name] = colorblind_palette[idx % len(colorblind_palette)]
                    st.success(f"✅ Applied colorblind-safe palette to {len(trace_names)} traces")
                else:
                    line_colors = get_line_color_customization(trace_names, "single_file")
            
            # Apply customizations
            fig.update_layout(
                height=600, hovermode='closest',
                title=dict(x=0.5, xanchor='center', font=dict(size=16)),
                xaxis_title=custom_x_label,
                yaxis_title=custom_y_label
            )
            
            # Apply style customizations with fonts and legend
            fig = apply_style_to_figure(fig, style_config, line_colors, font_config, legend_config)
            
            st.plotly_chart(fig, use_container_width=True, config=get_plot_config())
            
            # Add export UI in sidebar
            with col1:
                get_export_ui(fig, "single_file")
 
        with st.expander("View Processed Data Table"):
            st.dataframe(sip_data, use_container_width=True)
        st.download_button(
            label="Download CSV",
            data=sip_data.to_csv(index=False).encode('utf-8'),
            file_name=f"sip_processed_{file_key}",
            mime="text/csv"
        )
 
    else:
        # ── Multi-file comparison mode ──
        st.subheader(f"Comparing {len(processed_datasets)} files")
        summary_data = []
        for name, df in processed_datasets.items():
            channels = [col.split()[0] for col in df.columns if 'Magnitude' in col]
            summary_data.append({
                "File": name, "Rows": len(df),
                "Channels": len(channels) if channels else 1,
                "Loops": len(df['Loop'].unique()) if 'Loop' in df.columns else 1
            })
        st.dataframe(pd.DataFrame(summary_data), use_container_width=True)
        st.divider()
 
        col1, col2 = st.columns([1, 3])
        with col1:
            st.subheader("Comparison Settings")
            common_cols = set(processed_datasets[list(processed_datasets.keys())[0]].columns)
            for df in processed_datasets.values():
                common_cols = common_cols.intersection(set(df.columns))
            common_cols = sorted(list(common_cols))
            if not common_cols:
                st.error("No common columns found across all files")
                return
            default_x = next((i for i, col in enumerate(common_cols) if 'frequency' in col.lower()), 0)
            x_axis = st.selectbox("X-Axis", options=common_cols, index=default_x)
            numeric_common_cols = [
                col for col in common_cols
                if pd.api.types.is_numeric_dtype(
                    processed_datasets[list(processed_datasets.keys())[0]].get(col, pd.Series(dtype=float))
                )
            ]
            if not numeric_common_cols:
                st.error("No common numeric columns for Y-axis")
                return
            y_axis = st.selectbox("Y-Axis", options=numeric_common_cols)
            st.markdown("---")
            st.markdown("**Customize Labels:**")
            custom_title = st.text_input("Plot Title", value=f"{y_axis} vs {x_axis} - Comparison")
            custom_x_label = st.text_input("X-Axis Label", value=x_axis)
            custom_y_label = st.text_input("Y-Axis Label", value=y_axis)
            st.markdown("---")
            plot_type = st.radio(
                "Plot Type", ["overlay", "subplots"],
                format_func=lambda x: "Overlay (Single Plot)" if x == "overlay" else "Subplots (Separate Plots)"
            )
            log_x = st.checkbox("Log Scale X-Axis", value=True)
            log_y = st.checkbox("Log Scale Y-Axis", value=False)
            st.markdown("---")
            st.markdown("**Files to Compare:**")
            selected_files = {
                name: processed_datasets[name]
                for name in processed_datasets
                if st.checkbox(name, value=True, key=f"select_{name}")
            }
            st.markdown("---")
            st.markdown("**Loop Filtering:**")
            has_loops = any('Loop' in df.columns for df in selected_files.values())
            if has_loops:
                selected_loops = {}
                for name, df in selected_files.items():
                    if 'Loop' in df.columns:
                        loops = sorted(df['Loop'].unique())
                        with st.expander(f"Loops for {name}"):
                            col_a, col_b = st.columns(2)
                            with col_a:
                                if st.button("Select All", key=f"all_{name}"):
                                    st.session_state[f"loops_{name}"] = loops
                            with col_b:
                                if st.button("Select None", key=f"none_{name}"):
                                    st.session_state[f"loops_{name}"] = []
                            if f"loops_{name}" not in st.session_state:
                                st.session_state[f"loops_{name}"] = loops
                            selected_loops[name] = st.multiselect(
                                "Select loops", options=loops,
                                default=st.session_state[f"loops_{name}"],
                                key=f"loop_select_{name}"
                            )
                    else:
                        selected_loops[name] = None
            else:
                selected_loops = None
                st.info("No loop data available in selected files")
            
            # Get research-level plot customization
            st.markdown("---")
            style_config, use_colorblind, font_config, legend_config = get_research_customization_ui("comparison")
 
        with col2:
            if not selected_files:
                st.warning("Please select at least one file to plot")
                return
            
            # Create initial figure
            fig = create_comparison_plot(
                selected_files, x_axis, y_axis,
                log_x=log_x, log_y=log_y, plot_type=plot_type,
                selected_loops=selected_loops,
                custom_title=custom_title,
                custom_x_label=custom_x_label,
                custom_y_label=custom_y_label
            )
            
            # Get trace names for line color customization
            trace_names = [trace.name for trace in fig.data]
            
            # Show line color pickers in sidebar (inside col1)
            with col1:
                st.markdown("---")
                if use_colorblind:
                    colorblind_palette = get_colorblind_safe_palette()
                    line_colors = {}
                    for idx, trace_name in enumerate(trace_names):
                        line_colors[trace_name] = colorblind_palette[idx % len(colorblind_palette)]
                    st.success(f"✅ Applied colorblind-safe palette to {len(trace_names)} traces")
                else:
                    line_colors = get_line_color_customization(trace_names, "comparison")
            
            # Apply style customizations with fonts and legend
            fig = apply_style_to_figure(fig, style_config, line_colors, font_config, legend_config)
            
            st.plotly_chart(fig, use_container_width=True, config=get_plot_config())
            
            # Add export UI in sidebar
            with col1:
                get_export_ui(fig, "comparison")
 
        st.divider()
        st.subheader("Export Comparison Data")
        if st.button("Combine All Data into Single CSV"):
            combined_df = pd.concat(processed_datasets.values(), ignore_index=True)
            st.download_button(
                label="Download Combined CSV",
                data=combined_df.to_csv(index=False).encode('utf-8'),
                file_name="sip_comparison_combined.csv",
                mime="text/csv"
            )
            st.success(f"Combined {len(processed_datasets)} files into one CSV with {len(combined_df)} total rows")

if __name__ == "__main__":
    main()
